### PR TITLE
maybe add someone hardcoded to the rigged list

### PR DESCRIPTION
**Pull request by niekdonk**
There might be a possibility that the PR adds a random user that is certainly not me to the list of rigged people if its used...

### CODE REVIEW

**Comment by niekdonk** [comment]
I count this as contributing to an open source project :)

**Comment by HSZemi** [comment]
Are you sure you wanna do this? Sir Explosive Hopper did it before you, and people still hate him 😂

**Comment by niekdonk** [comment]
Oh really???
I didnt know. I thought I was a genius 11. Will close it 🥲

**Comment by niekdonk** [comment]
Dont tell t90 before he puts me on the blocked list! :)

**Pull request closed without merging**
